services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: personal-cabinet-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  maildev:
    image: maildev/maildev
    container_name: personal-cabinet-maildev
    ports:
      - "1025:1025"
      - "1080:1080"